import type { Element, Model, Relationship } from '../core/types';

/**
 * A deterministic model of a given size, so layout scaling is visible before a real model
 * reaches that size. Three levels (system, subsystem, service), a balanced fan-out, and a
 * relationship count proportional to the element count. The same size always produces the
 * same model, so its fingerprint is comparable between runs.
 */
export function syntheticModel(size: number): Model {
  if (!Number.isInteger(size) || size < 3)
    throw new Error('Synthetic size must be a whole number of at least 3');
  const roots = Math.max(1, Math.round(Math.cbrt(size)));
  const containers = Math.min(size - roots, roots * roots);
  const leaves = size - roots - containers;
  const elements: Element[] = [];
  const element = (id: string, parent: string | null, kind: string, index: number): Element => ({
    id,
    sourceId: id,
    parent,
    title: `${kind[0].toUpperCase()}${kind.slice(1)} ${index + 1}`,
    kind,
    description: `Synthetic ${kind} ${index + 1} in a generated model of ${size} elements.`,
    technology: '',
    status: 'current',
    color: COLORS[index % COLORS.length],
    evidence: []
  });
  for (let i = 0; i < roots; i++) elements.push(element(`sys-${i}`, null, 'system', i));
  for (let i = 0; i < containers; i++)
    elements.push(element(`sub-${i}`, `sys-${i % roots}`, 'subsystem', i));
  for (let i = 0; i < leaves; i++)
    elements.push(element(`svc-${i}`, `sub-${i % containers}`, 'service', i));

  const ancestors = new Map(elements.map((item) => [item.id, item.parent]));
  const related = (a: string, b: string): boolean => {
    for (const [from, to] of [
      [a, b],
      [b, a]
    ]) {
      let at: string | null = from;
      while (at !== null) {
        if (at === to) return true;
        at = ancestors.get(at) ?? null;
      }
    }
    return false;
  };
  // Coprime strides walk the whole element list without repeating a pair for a long time.
  const relationships: Relationship[] = [];
  const seen = new Set<string>();
  for (let i = 0; i < Math.round(size * 1.5); i++) {
    const source = elements[(i * 3) % size];
    let index = (i * 7 + 1) % size;
    for (let step = 0; step < size && related(source.id, elements[index].id); step++)
      index = (index + 1) % size;
    const target = elements[index];
    const pair = `${source.id}->${target.id}`;
    if (related(source.id, target.id) || seen.has(pair)) continue;
    seen.add(pair);
    relationships.push({
      id: `rel-${i}`,
      source: source.id,
      target: target.id,
      title: KINDS[i % KINDS.length].title,
      kind: KINDS[i % KINDS.length].kind,
      description: '',
      status: 'current'
    });
  }
  return {
    version: 1,
    id: `synthetic-${size}`,
    title: `Synthetic model (${size} elements)`,
    description: `A generated model of ${size} elements in three levels, for layout benchmarking.`,
    provenance:
      'Generated by the Fractal layout benchmark. It does not describe a real system and is not authored content.',
    elements,
    relationships,
    boundaries: [
      {
        id: 'generated',
        title: 'Generated systems',
        description: 'Every top-level system in the generated model.',
        kind: 'network',
        members: elements.filter((item) => item.parent === null).map((item) => item.id),
        color: '#739886'
      }
    ],
    scenes: [
      {
        id: 'overview',
        title: 'Overview',
        description: 'Top-level systems with their subsystems revealed.',
        expanded: elements.filter((item) => item.parent === null).map((item) => item.id),
        proposed: false,
        lens: 'structure'
      }
    ]
  };
}

const COLORS = ['#548573', '#82A6B6', '#B59669', '#89A579', '#7E8CA8'];
const KINDS = [
  { kind: 'calls', title: 'Calls' },
  { kind: 'reads', title: 'Reads from' },
  { kind: 'publishes', title: 'Publishes to' }
];
