// Deterministic linked-composition benchmark fixtures and the composition measurement harness.
// Everything here is generated from code with no random seed, so the recorded digest pins the
// exact sources. Real repository models are never bundled: the only local steel-thread input is a
// configured catalog passed explicitly on the command line. This module is imported by
// `scripts/bench.ts`, `scripts/bench-browser.ts` and `tests/bench.test.ts`.
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { performance } from 'node:perf_hooks';
import {
  geometryFingerprint,
  percentile,
  qualityMetrics,
  rowKey,
  type BenchEngineId,
  type QualityMetrics,
  type StageStats
} from '../src/lib/bench';
import { compose } from '../src/lib/composition/compose';
import { staticResolver, type ProjectSnapshot } from '../src/lib/composition/snapshot';
import { stateFromComposition } from '../src/lib/composition/state';
import type { ComposedDiagram } from '../src/lib/composition/types';
import { layout } from '../src/lib/core/layout';
import type { Diagram } from '../src/lib/core/types';
import {
  catalogResolver,
  clearModelCache,
  loadDirectory,
  modelCacheStats,
  resolveProject,
  snapshotOf,
  type CatalogOptions
} from '../src/lib/server/models';

/**
 * The stage timings that only a composition has; the single-model bench keeps its own set.
 * `compose` is the public placement/routing boundary over already-parsed snapshots and includes
 * the local layout it re-runs internally; `place` is `compose` minus the separately measured
 * `local` pass, so frame placement and bridge routing can be read without double-counting layout.
 */
export const COMPOSITION_STAGES = [
  'resolve',
  'parse',
  'local',
  'compose',
  'place',
  'serialize'
] as const;
export type CompositionStage = (typeof COMPOSITION_STAGES)[number];

export interface FixtureModel {
  id: string;
  model: string;
  companion: Record<string, unknown>;
  links: LinksFile | null;
}

export interface FixtureSpec {
  id: string;
  title: string;
  description: string;
  root: string;
  composition: string;
}

export interface GeneratedFixtureSources {
  fixtures: FixtureSpec[];
  models: FixtureModel[];
}

interface LinkEntry {
  id: string;
  from?: string;
  target: { model: string; scene?: string };
  title: string;
}
interface ConnectionEntry {
  id: string;
  source: { model: string; element: string };
  target: { model: string; element: string };
  title: string;
  kind: string;
  status: 'current' | 'proposed';
  description: string;
  evidence: string[];
}
interface CompositionEntry {
  id: string;
  title: string;
  rootScene?: string;
  projects: { model: string; scene?: string; mode: 'open' | 'collapsed' }[];
}
export interface LinksFile {
  version: 1;
  links: LinkEntry[];
  connections: ConnectionEntry[];
  compositions: CompositionEntry[];
}

interface ModelShape {
  id: string;
  title: string;
  description: string;
  groups: number;
  perGroup: number;
  relationships: number;
  longTitles?: boolean;
  trust?: boolean;
  /**
   * When set, emit this many deterministic edge families instead of the legacy relationship
   * sequence. Each family gives every child one outgoing edge, so a model can exceed the
   * one-edge-per-child ceiling the legacy generator imposes. Legacy shapes leave it unset.
   */
  relationshipFamilies?: number;
}

const provenance =
  'Generated by the Fractal linked-diagram benchmark. It describes no real system and is not authored content.';

function modelSource(shape: ModelShape): FixtureModel {
  const lines = [
    'specification {',
    '  element group',
    '  element component',
    '  relationship calls',
    '}',
    'model {'
  ];
  const container = (group: number): string =>
    shape.longTitles
      ? `${shape.title} operational subsystem number ${group + 1} with a deliberately long authored name`
      : `Group ${group + 1}`;
  for (let g = 0; g < shape.groups; g++) {
    lines.push(`  g${g} = group '${container(g)}' {`);
    lines.push(`    metadata { uid 'g${g}' }`);
    for (let c = 0; c < shape.perGroup; c++) {
      const child = shape.longTitles
        ? `Component ${g + 1}.${c + 1} whose descriptive title runs well past a comfortable card width`
        : `Component ${g + 1}.${c + 1}`;
      lines.push(`    c${c} = component '${child}' { metadata { uid 'g${g}.c${c}' } }`);
    }
    lines.push('  }');
  }
  const total = shape.groups * shape.perGroup;
  const seen = new Set<string>();
  const pushRelationship = (a: number, b: number, index: number): void => {
    const ga = Math.floor(a / shape.perGroup);
    const ca = a % shape.perGroup;
    const gb = Math.floor(b / shape.perGroup);
    const cb = b % shape.perGroup;
    lines.push(
      `  g${ga}.c${ca} -[calls]-> g${gb}.c${cb} 'Calls ${index + 1}' { metadata { uid 'r${index}' } }`
    );
  };
  if (shape.relationshipFamilies !== undefined) {
    // Deterministic dense edges: family `f` gives every child one edge to `a * (7 + 4f) + 1`.
    let index = 0;
    for (let family = 0; family < shape.relationshipFamilies && total > 1; family++) {
      const step = 7 + family * 4;
      for (let a = 0; a < total; a++) {
        const b = (a * step + 1) % total;
        if (a === b) continue;
        const pair = `${a}->${b}`;
        if (seen.has(pair)) continue;
        seen.add(pair);
        pushRelationship(a, b, index++);
      }
    }
  } else {
    for (let i = 0; i < shape.relationships && total > 1; i++) {
      const a = (i * 3) % total;
      let b = (i * 7 + 1) % total;
      if (a === b) b = (b + 1) % total;
      if (a === b) continue;
      const pair = `${a}->${b}`;
      if (seen.has(pair)) continue;
      seen.add(pair);
      pushRelationship(a, b, i);
    }
  }
  lines.push('}');
  const groups = Array.from({ length: shape.groups }, (_value, g) => `g${g}`);
  const boundaries = shape.trust
    ? [
        {
          id: 'trust-core',
          title: 'Shared build trust',
          description: 'Overlaps the runtime trust set on purpose.',
          kind: 'permission',
          members: [groupChild(0, 0), groupChild(1, 0), groupChild(2, 0)],
          color: '#739886'
        },
        {
          id: 'trust-runtime',
          title: 'Runtime permissions',
          description: 'Overlaps the shared build trust set on purpose.',
          kind: 'permission',
          members: [groupChild(1, 0), groupChild(2, 0), groupChild(0, 1)],
          color: '#82A6B6'
        },
        {
          id: 'trust-audit',
          title: 'Audit visibility',
          description: 'Overlaps both other membership claims.',
          kind: 'permission',
          members: [groupChild(2, 0), groupChild(0, 0), groupChild(1, 1)],
          color: '#B59669'
        }
      ]
    : [];
  const companion = {
    version: 1,
    id: shape.id,
    title: shape.title,
    description: shape.description,
    provenance,
    boundaries,
    scenes: [
      {
        id: 'overview',
        title: 'Overview',
        description: shape.description,
        expanded: groups,
        proposed: false,
        lens: shape.trust ? 'trust' : 'structure'
      }
    ]
  };
  return { id: shape.id, model: `${lines.join('\n')}\n`, companion, links: null };
}

function groupChild(group: number, child: number): string {
  return `g${group}.c${child}`;
}

/** Every element UID of a generated shape, containers first, in declaration order. */
export function elementIds(shape: ModelShape): string[] {
  const ids: string[] = [];
  for (let g = 0; g < shape.groups; g++) {
    ids.push(`g${g}`);
    for (let c = 0; c < shape.perGroup; c++) ids.push(groupChild(g, c));
  }
  return ids;
}

function linksFile(
  links: LinkEntry[],
  connections: ConnectionEntry[] = [],
  compositions: CompositionEntry[] = []
): LinksFile {
  return { version: 1, links, connections, compositions };
}

function link(id: string, target: string, from?: string): LinkEntry {
  return { id, ...(from === undefined ? {} : { from }), target: { model: target }, title: target };
}

function connection(
  id: string,
  source: string,
  sourceElement: string,
  target: string,
  targetElement: string,
  title: string,
  kind = 'calls'
): ConnectionEntry {
  return {
    id,
    source: { model: source, element: sourceElement },
    target: { model: target, element: targetElement },
    title,
    kind,
    status: 'current',
    description: `Generated ${kind} claim from ${source} to ${target}.`,
    evidence: [`src/${source}.ts`]
  };
}

const ROOT_SHAPE: Omit<ModelShape, 'id' | 'title' | 'description'> = {
  groups: 2,
  perGroup: 1,
  relationships: 1
};

function rootModel(id: string, title: string, links: LinksFile): FixtureModel {
  const model = modelSource({ id, title, description: `${title} benchmark root.`, ...ROOT_SHAPE });
  return { ...model, links };
}

/** A root with 20 authored links that are never opened: only the root may ever be parsed. */
function unopenedFixture(): GeneratedFixtureSources {
  const targets = Array.from(
    { length: 20 },
    (_value, index) => `unopened-target-${String(index).padStart(2, '0')}`
  );
  const models: FixtureModel[] = [
    rootModel(
      'unopened-hub',
      'Unopened hub',
      linksFile(
        targets.map((target, index) => link(`link-${index}`, target, 'g0')),
        [],
        [{ id: 'root-only', title: 'Root only', rootScene: 'overview', projects: [] }]
      )
    )
  ];
  for (const target of targets)
    models.push(
      modelSource({
        id: target,
        title: target,
        description: 'Unopened link target.',
        groups: 1,
        perGroup: 1,
        relationships: 0
      })
    );
  return {
    fixtures: [
      {
        id: 'unopened',
        title: 'Root with 20 unopened links',
        description: 'A root whose 20 authored links are never opened; zero foreign parses.',
        root: 'unopened-hub',
        composition: 'root-only'
      }
    ],
    models
  };
}

/** Three foreign projects with 100 visible nodes each, fully linked with the root. */
function visibleFixture(): GeneratedFixtureSources {
  const root = 'visible-root';
  const foreign = ['visible-a', 'visible-b', 'visible-c'];
  const all = [root, ...foreign];
  const models: FixtureModel[] = [];
  for (const model of all) {
    const isRoot = model === root;
    const shape: ModelShape = isRoot
      ? { id: model, title: 'Visible root', description: 'Visible root.', ...ROOT_SHAPE }
      : {
          id: model,
          title: `Visible ${model.slice(-1).toUpperCase()}`,
          description: 'One hundred visible nodes.',
          groups: 10,
          perGroup: 9,
          relationships: 100
        };
    const links: LinkEntry[] = all
      .filter((other) => other !== model)
      .map((other) => link(`link-${other}`, other, 'g0'));
    const connections: ConnectionEntry[] = all
      .filter((other) => other !== model)
      .map((other) => connection(`to-${other}`, model, 'g0', other, 'g0', `Calls ${other}`));
    const source = modelSource(shape);
    models.push({
      ...source,
      links: linksFile(
        links,
        connections,
        isRoot
          ? [
              {
                id: 'all-open',
                title: 'All projects open',
                rootScene: 'overview',
                projects: foreign.map((model) => ({ model, scene: 'overview', mode: 'open' }))
              }
            ]
          : []
      )
    });
  }
  return {
    fixtures: [
      {
        id: 'visible',
        title: 'Three projects, 100 visible nodes each, fully linked',
        description: 'Four open projects with every ordered pair claimed.',
        root,
        composition: 'all-open'
      }
    ],
    models
  };
}

/** Ten 1,000-element projects that participate collapsed: load scale with no local layout. */
function loadedFixture(): GeneratedFixtureSources {
  const root = 'loaded-root';
  const foreign = Array.from({ length: 10 }, (_value, index) => `loaded-p${index}`);
  const models: FixtureModel[] = [
    rootModel(
      root,
      'Loaded root',
      linksFile(
        foreign.map((model) => link(`link-${model}`, model, 'g0')),
        foreign.map((model) =>
          connection(`to-${model}`, root, 'g0', model, 'g0', `Loads ${model}`)
        ),
        [
          {
            id: 'collapsed',
            title: 'Ten collapsed projects',
            rootScene: 'overview',
            projects: foreign.map((model) => ({ model, scene: 'overview', mode: 'collapsed' }))
          }
        ]
      )
    )
  ];
  for (const model of foreign) {
    const source = modelSource({
      id: model,
      title: model,
      description: 'One thousand loaded elements.',
      groups: 10,
      perGroup: 99,
      relationships: 2000
    });
    models.push({ ...source, links: linksFile([link(`link-${root}`, root, 'g0')]) });
  }
  return {
    fixtures: [
      {
        id: 'loaded',
        title: 'Ten projects of 1,000 loaded elements, collapsed',
        description: 'Parse scale with collapsed views: no local layout runs.',
        root,
        composition: 'collapsed'
      }
    ],
    models
  };
}

/** Hundreds of claims between two open projects, in both directions. */
function bridgesFixture(): GeneratedFixtureSources {
  const root = 'bridge-root';
  const a = 'bridge-a';
  const b = 'bridge-b';
  const aShape: ModelShape = {
    id: a,
    title: 'Bridge alpha',
    description: 'Dense bridge source.',
    groups: 10,
    perGroup: 9,
    relationships: 150
  };
  const bShape: ModelShape = { ...aShape, id: b, title: 'Bridge beta' };
  const aIds = elementIds(aShape);
  const bIds = elementIds(bShape);
  const connections: ConnectionEntry[] = [];
  for (let i = 0; i < 150; i++)
    connections.push(
      connection(
        `a-${i}`,
        a,
        aIds[i % aIds.length],
        b,
        bIds[(i * 7 + 3) % bIds.length],
        `A calls B ${i + 1}`
      )
    );
  for (let i = 0; i < 150; i++)
    connections.push(
      connection(
        `b-${i}`,
        b,
        bIds[i % bIds.length],
        a,
        aIds[(i * 7 + 3) % aIds.length],
        `B calls A ${i + 1}`
      )
    );
  const models: FixtureModel[] = [
    rootModel(
      root,
      'Dense bridge root',
      linksFile(
        [link('link-a', a, 'g0'), link('link-b', b, 'g0')],
        [],
        [
          {
            id: 'dense',
            title: 'Dense bridges',
            rootScene: 'overview',
            projects: [
              { model: a, scene: 'overview', mode: 'open' },
              { model: b, scene: 'overview', mode: 'open' }
            ]
          }
        ]
      )
    ),
    {
      ...modelSource(aShape),
      links: linksFile(
        [link('link-b', b, 'g0')],
        connections.filter((c) => c.source.model === a)
      )
    },
    {
      ...modelSource(bShape),
      links: linksFile(
        [link('link-a', a, 'g0')],
        connections.filter((c) => c.source.model === b)
      )
    }
  ];
  return {
    fixtures: [
      {
        id: 'bridges',
        title: 'Dense cross-project bridges',
        description: 'Three hundred claims between two open projects.',
        root,
        composition: 'dense'
      }
    ],
    models
  };
}

interface ProjectSetSpec {
  id: string;
  title: string;
  description: string;
  root: string;
  composition: string;
  projects: string[];
  /** Directed edges between projects, as `[source, target]` pairs. */
  edges: [string, string][];
  shapes: Record<string, ModelShape>;
  /** Optional override for a claim's title, so a fixture can force long wrapped labels. */
  titleFor?: (source: string, target: string) => string;
}

/** A small directed project graph with exactly the listed claims. */
function projectSet(spec: ProjectSetSpec): GeneratedFixtureSources {
  const all = [spec.root, ...spec.projects];
  const models: FixtureModel[] = all.map((model) => {
    const shape = spec.shapes[model];
    const foreign = all.filter((other) => other !== model);
    const outgoing = spec.edges.filter(([source]) => source === model);
    const outgoingTargets = new Set(outgoing.map(([, target]) => target));
    const links = foreign
      .filter((other) => outgoingTargets.has(other) || (model === spec.root && other !== spec.root))
      .map((other) => link(`link-${other}`, other, 'g0'));
    const connections = outgoing.map(([, target], index) =>
      connection(
        `call-${index}`,
        model,
        'g0',
        target,
        'g0',
        spec.titleFor ? spec.titleFor(model, target) : `${model} calls ${target}`
      )
    );
    if (model === spec.root)
      return rootModel(
        model,
        shape.title,
        linksFile(links, connections, [
          {
            id: spec.composition,
            title: spec.title,
            rootScene: 'overview',
            projects: spec.projects.map((other) => ({
              model: other,
              scene: 'overview',
              mode: 'open' as const
            }))
          }
        ])
      );
    return { ...modelSource(shape), links: linksFile(links, connections) };
  });
  return {
    fixtures: [
      {
        id: spec.id,
        title: spec.title,
        description: spec.description,
        root: spec.root,
        composition: spec.composition
      }
    ],
    models
  };
}

function smallShape(id: string, title = id): ModelShape {
  return {
    id,
    title,
    description: `${title} benchmark project.`,
    groups: 2,
    perGroup: 1,
    relationships: 1
  };
}

function chainFixture(): GeneratedFixtureSources {
  const projects = Array.from({ length: 8 }, (_value, index) => `chain-c${index}`);
  const shapes: Record<string, ModelShape> = {};
  for (const model of projects) shapes[model] = smallShape(model, `Chain ${model.slice(-1)}`);
  const edges: [string, string][] = [];
  for (let i = 0; i < projects.length - 1; i++) edges.push([projects[i], projects[i + 1]]);
  return projectSet({
    id: 'chain',
    title: 'Chain of eight projects',
    description: 'A linear eight-project chain with seven bridges.',
    root: projects[0],
    composition: 'chain',
    projects: projects.slice(1),
    edges,
    shapes
  });
}

function cycleFixture(): GeneratedFixtureSources {
  const projects = ['cycle-c0', 'cycle-c1', 'cycle-c2'];
  const shapes: Record<string, ModelShape> = {};
  for (const model of projects) shapes[model] = smallShape(model, `Cycle ${model.slice(-1)}`);
  return projectSet({
    id: 'cycle',
    title: 'Project cycle',
    description: 'A three-project cycle that reuses the root frame.',
    root: projects[0],
    composition: 'cycle',
    projects: projects.slice(1),
    edges: [
      [projects[0], projects[1]],
      [projects[1], projects[2]],
      [projects[2], projects[0]]
    ],
    shapes
  });
}

function diamondFixture(): GeneratedFixtureSources {
  const projects = ['diamond-c0', 'diamond-c1', 'diamond-c2', 'diamond-c3'];
  const shapes: Record<string, ModelShape> = {};
  for (const model of projects) shapes[model] = smallShape(model, `Diamond ${model.slice(-1)}`);
  return projectSet({
    id: 'diamond',
    title: 'Project diamond',
    description: 'A diamond whose shared target is reused once.',
    root: projects[0],
    composition: 'diamond',
    projects: projects.slice(1),
    edges: [
      [projects[0], projects[1]],
      [projects[0], projects[2]],
      [projects[1], projects[3]],
      [projects[2], projects[3]]
    ],
    shapes
  });
}

/** Long titles and overlapping trust memberships under the trust lens. */
function labelsFixture(): GeneratedFixtureSources {
  const root = 'labels-root';
  const foreign = ['labels-alpha', 'labels-beta'];
  const shapes: Record<string, ModelShape> = {
    [root]: smallShape(root, 'Labels root with a very long authored project title that must wrap')
  };
  for (const model of foreign)
    shapes[model] = {
      id: model,
      title: `${model} with a deliberately long authored title that must wrap across the frame`,
      description: 'Long labels and overlapping trust memberships.',
      groups: 3,
      perGroup: 3,
      relationships: 6,
      longTitles: true,
      trust: true
    };
  return projectSet({
    id: 'labels',
    title: 'Long labels and overlapping trust',
    description: 'Long project and claim titles with overlapping trust memberships.',
    root,
    composition: 'labels',
    projects: foreign,
    edges: [
      [root, foreign[0]],
      [root, foreign[1]],
      [foreign[0], foreign[1]],
      [foreign[1], foreign[0]]
    ],
    shapes,
    titleFor: (source, target) =>
      `Synchronizes ${source} with ${target} across a long-lived authenticated bidirectional channel`
  });
}

/** Two open projects sized for the pan/zoom gate: about 300 visible nodes and 600 visible edges. */
function scaleFixture(): GeneratedFixtureSources {
  const root = 'scale-root';
  const foreign = 'scale-alpha';
  const shape: ModelShape = {
    id: foreign,
    title: 'Scale alpha',
    description: 'Eight containers and 288 children with two dense relationship families.',
    groups: 8,
    perGroup: 36,
    relationships: 0,
    relationshipFamilies: 2
  };
  return {
    fixtures: [
      {
        id: 'scale',
        title: 'Two-project 300-node, 600-edge composition',
        description: 'An open two-project composition sized for the pan/zoom gate.',
        root,
        composition: 'scale-open'
      }
    ],
    models: [
      rootModel(
        root,
        'Scale root',
        linksFile(
          [link('link-alpha', foreign, 'g0')],
          [connection('to-alpha', root, 'g0', foreign, 'g0', 'Calls scale alpha')],
          [
            {
              id: 'scale-open',
              title: 'Scale open pair',
              rootScene: 'overview',
              projects: [{ model: foreign, scene: 'overview', mode: 'open' }]
            }
          ]
        )
      ),
      { ...modelSource(shape), links: linksFile([link('link-root', root, 'g0')]) }
    ]
  };
}

const FIXTURE_BUILDERS: Record<string, () => GeneratedFixtureSources> = {
  unopened: unopenedFixture,
  visible: visibleFixture,
  loaded: loadedFixture,
  bridges: bridgesFixture,
  chain: chainFixture,
  cycle: cycleFixture,
  diamond: diamondFixture,
  labels: labelsFixture,
  scale: scaleFixture
};

/**
 * The fixtures the default matrix measures. `scale` is a registered builder but not part of the
 * default matrix: it is large and exists for the browser pan/zoom journey, so it is requested by
 * name. Keeping it out of the default set keeps the matrix digest stable.
 */
export const FIXTURE_IDS = [
  'unopened',
  'visible',
  'loaded',
  'bridges',
  'chain',
  'cycle',
  'diamond',
  'labels'
];

/** Build the requested fixtures (all by default). Model IDs are fixture-specific, so any subset works. */
export function generateFixtures(ids?: readonly string[]): GeneratedFixtureSources {
  const wanted = ids === undefined || ids.length === 0 ? FIXTURE_IDS : [...ids];
  const fixtures: FixtureSpec[] = [];
  const byId = new Map<string, FixtureModel>();
  for (const fixture of wanted) {
    const build = FIXTURE_BUILDERS[fixture];
    if (!build)
      throw new Error(
        `Unknown fixture: ${fixture} (known: ${Object.keys(FIXTURE_BUILDERS).join(', ')})`
      );
    const generated = build();
    fixtures.push(...generated.fixtures);
    for (const model of generated.models) {
      if (byId.has(model.id)) throw new Error(`Duplicate generated model ID: ${model.id}`);
      byId.set(model.id, model);
    }
  }
  return {
    fixtures,
    models: [...byId.values()].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
  };
}

/**
 * Two structurally identical roots for the first-paint A/B: `paint-hub` authors 20 links that
 * are never opened, `paint-plain` authors none. Both keep a root-only composition, so the only
 * difference a browser sees is whether the root lists links. The 20 targets exist so link listing
 * reports real availability rather than failures.
 */
export const PAINT_ROOTS = { links: 'paint-hub', plain: 'paint-plain' } as const;

export function paintSources(): GeneratedFixtureSources {
  const targets = Array.from(
    { length: 20 },
    (_value, index) => `paint-target-${String(index).padStart(2, '0')}`
  );
  const rootOnly: CompositionEntry[] = [
    { id: 'root-only', title: 'Root only', rootScene: 'overview', projects: [] }
  ];
  const models: FixtureModel[] = [
    {
      ...modelSource({
        id: PAINT_ROOTS.links,
        title: 'Paint hub',
        description: 'Twenty authored links that are never opened.',
        ...ROOT_SHAPE
      }),
      links: linksFile(
        targets.map((target, index) => link(`paint-link-${index}`, target, 'g0')),
        [],
        rootOnly
      )
    },
    {
      ...modelSource({
        id: PAINT_ROOTS.plain,
        title: 'Paint plain',
        description: 'No authored links.',
        ...ROOT_SHAPE
      }),
      links: linksFile([], [], rootOnly)
    }
  ];
  for (const target of targets)
    models.push(
      modelSource({
        id: target,
        title: target,
        description: 'First-paint link target.',
        groups: 1,
        perGroup: 1,
        relationships: 0
      })
    );
  return { fixtures: [], models };
}

/**
 * A content hash over every generated source, in sorted model order. It pins the generator, so a
 * changed fixture changes the digest even though no random seed is used.
 */
export function fixtureDigest(sources: GeneratedFixtureSources): string {
  const hash = createHash('sha256');
  for (const model of [...sources.models].sort((a, b) =>
    a.id < b.id ? -1 : a.id > b.id ? 1 : 0
  )) {
    hash.update(model.id).update('\0').update(model.model).update('\0');
    hash.update(JSON.stringify(model.companion)).update('\0');
    hash.update(model.links === null ? '' : JSON.stringify(model.links)).update('\0');
  }
  for (const fixture of sources.fixtures) hash.update(JSON.stringify(fixture)).update('\0');
  return hash.digest('hex');
}

export interface WrittenFixtures {
  catalog: string;
  directories: Record<string, string>;
  bytes: number;
}

/** Write every generated model and the catalog under `root`. The caller owns and removes `root`. */
export async function writeFixtures(
  sources: GeneratedFixtureSources,
  root: string
): Promise<WrittenFixtures> {
  const directories: Record<string, string> = {};
  let bytes = 0;
  for (const model of sources.models) {
    const directory = join(root, model.id);
    await mkdir(directory, { recursive: true });
    const companion = JSON.stringify(model.companion, null, 2) + '\n';
    await writeFile(join(directory, 'model.c4'), model.model);
    await writeFile(join(directory, 'fractal.json'), companion);
    bytes += Buffer.byteLength(model.model) + Buffer.byteLength(companion);
    if (model.links !== null) {
      const links = JSON.stringify(model.links, null, 2) + '\n';
      await writeFile(join(directory, 'links.json'), links);
      bytes += Buffer.byteLength(links);
    }
    directories[model.id] = directory;
  }
  const projects = sources.models.map((model) => ({
    id: model.id,
    directory: directories[model.id]
  }));
  const catalog = join(root, 'catalog.json');
  const catalogText = JSON.stringify({ version: 1, projects }, null, 2) + '\n';
  await writeFile(catalog, catalogText);
  bytes += Buffer.byteLength(catalogText);
  return { catalog, directories, bytes };
}

const fixed = (value: number): string => {
  const rounded = Math.round(value * 100) / 100;
  return (rounded === 0 ? 0 : rounded).toFixed(2);
};

const byModel = (a: { model: string }, b: { model: string }): number =>
  a.model < b.model ? -1 : a.model > b.model ? 1 : 0;
const byOwnerId = (
  a: ComposedDiagram['bridges'][number],
  b: ComposedDiagram['bridges'][number]
): number =>
  a.owner < b.owner ? -1 : a.owner > b.owner ? 1 : a.id < b.id ? -1 : a.id > b.id ? 1 : 0;

/** Frames, bridge points and per-project local geometry hashes, in a deterministic order. */
export function compositionFingerprint(composed: ComposedDiagram): string {
  const lines: string[] = [];
  for (const project of [...composed.projects].sort(byModel)) {
    const frame = project.frame;
    lines.push(
      `project ${project.model} ${fixed(frame.x)} ${fixed(frame.y)} ${fixed(frame.width)} ${fixed(frame.height)} ${project.mode} ${project.diagram ? geometryFingerprint(project.diagram) : 'collapsed'}`
    );
  }
  for (const bridge of [...composed.bridges].sort(byOwnerId)) {
    const points = bridge.points.map((point) => `${fixed(point.x)},${fixed(point.y)}`).join(' ');
    lines.push(
      `bridge ${bridge.owner} ${bridge.id} ${points} ${bridge.source.representative.kind} ${bridge.target.representative.kind}`
    );
  }
  lines.push(`size ${fixed(composed.width)} ${fixed(composed.height)}`);
  return createHash('sha256').update(lines.join('\n')).digest('hex');
}

/** Quality over the whole composed canvas: local nodes and edges, then bridges as routed edges. */
export function composedQuality(composed: ComposedDiagram): QualityMetrics {
  const nodes: Diagram['nodes'] = [];
  const edges: Diagram['edges'] = [];
  for (const project of composed.projects) {
    if (!project.diagram) continue;
    for (const node of project.diagram.nodes)
      nodes.push({
        ...node,
        x: node.x + project.content.x,
        y: node.y + project.content.y
      });
    for (const edge of project.diagram.edges)
      edges.push({
        ...edge,
        id: `${project.model}:${edge.id}`,
        points: edge.points.map((point) => ({
          x: point.x + project.content.x,
          y: point.y + project.content.y
        })),
        label: {
          x: edge.label.x + project.content.x,
          y: edge.label.y + project.content.y
        }
      });
  }
  for (const bridge of composed.bridges)
    edges.push({
      id: `bridge:${bridge.owner}:${bridge.id}`,
      source: bridge.source.element,
      target: bridge.target.element,
      title: bridge.title,
      kind: bridge.kind,
      description: bridge.description,
      status: bridge.status,
      underlying: [bridge.id],
      points: bridge.points,
      label: bridge.label,
      labelLines: bridge.labelLines
    });
  return qualityMetrics({
    nodes,
    edges,
    width: composed.width,
    height: composed.height,
    state: {} as Diagram['state']
  });
}

export interface CompositionCounts {
  projects: number;
  loadedElements: number;
  loadedRelationships: number;
  visibleNodes: number;
  visibleEdges: number;
  bridges: number;
  stubs: number;
  diagnostics: number;
  cacheHits: number;
  cacheMisses: number;
  cacheEntries: number;
}

/** A composition row is a `BenchRow` plus composition counts, estimated bytes and a cold sample. */
export interface CompositionRow {
  model: string;
  view: 'composition';
  engine: BenchEngineId;
  source: string;
  nodes: number;
  edges: number;
  width: number;
  height: number;
  iterations: number;
  stages: Partial<Record<CompositionStage, StageStats>>;
  fingerprint: string;
  quality: QualityMetrics;
  counts: CompositionCounts;
  bytes: number;
  coldParseMs: number | null;
  commit: string | null;
  timestamp: string;
}

export interface MeasureCompositionOptions {
  /** Path to a catalog.json; only this catalog is ever read. */
  catalog: string;
  root: string;
  composition: string;
  /** Row identity: a fixture ID for generated fixtures, or a local label. */
  label: string;
  iterations: number;
}

export interface CompositionRun {
  row: CompositionRow;
  composed: ComposedDiagram;
}

interface CompositionPass {
  durations: Record<CompositionStage, number>;
  composed: ComposedDiagram;
  snapshots: ProjectSnapshot[];
  bytes: number;
  engine: BenchEngineId;
}

const round = (value: number, places: number): number => {
  const factor = 10 ** places;
  return Math.round(value * factor) / factor;
};

function summarize(
  runs: readonly CompositionPass[]
): Partial<Record<CompositionStage, StageStats>> {
  const stages: Partial<Record<CompositionStage, StageStats>> = {};
  for (const stage of COMPOSITION_STAGES) {
    const samples = runs.map((run) => run.durations[stage]);
    if (!samples.length) continue;
    stages[stage] = {
      p50: round(percentile(samples, 0.5), 3),
      p95: round(percentile(samples, 0.95), 3),
      samples: samples.length
    };
  }
  return stages;
}

/** One full composition pass: catalog resolution, parse, local layout, place/route and serialize. */
async function compositionPass(
  root: string,
  composition: string,
  participating: string[],
  catalog: CatalogOptions
): Promise<CompositionPass> {
  const durations: Record<CompositionStage, number> = {
    resolve: 0,
    parse: 0,
    local: 0,
    compose: 0,
    place: 0,
    serialize: 0
  };
  const directories = new Map<string, string>();
  let start = performance.now();
  for (const model of participating)
    directories.set(model, (await resolveProject(model, catalog)).entry.directory);
  durations.resolve = performance.now() - start;

  const snapshots = new Map<string, ProjectSnapshot>();
  start = performance.now();
  for (const model of participating)
    snapshots.set(model, snapshotOf(await loadDirectory(directories.get(model)!)));
  durations.parse = performance.now() - start;

  const rootSnapshot = snapshots.get(root)!;
  const state = stateFromComposition(rootSnapshot, composition, (model) => snapshots.get(model));
  start = performance.now();
  for (const project of state.projects) {
    if (project.mode === 'collapsed') continue;
    const snapshot = snapshots.get(project.model)!;
    await layout(snapshot.model, {
      ...project.view,
      theme: state.theme,
      layout: state.layout
    });
  }
  durations.local = performance.now() - start;

  start = performance.now();
  const composed = await compose(staticResolver(snapshots.values()), state);
  durations.compose = performance.now() - start;
  // `compose` runs local layout again; subtract the local pass just measured so `place` reports
  // frame placement and bridge routing only. Splitting those two apart needs an internal seam the
  // composition core does not expose yet.
  durations.place = Math.max(0, durations.compose - durations.local);

  start = performance.now();
  const json = JSON.stringify(composed);
  durations.serialize = performance.now() - start;

  return {
    durations,
    composed,
    snapshots: [...snapshots.values()],
    bytes: Buffer.byteLength(json),
    engine: state.layout
  };
}

/**
 * Measure one composition: a cold parse sample after clearing the model cache, one discardable
 * warm-up, then `iterations` timed passes. Resolution, parse, local layout, placement/routing and
 * serialization are timed separately; counts, bytes and a deterministic geometry fingerprint are
 * reported. Measured `parse` passes are warm stamp lookups, exactly like the single-model bench's
 * `load`; the cold sample is the separate cold evidence.
 */
export async function measureComposition(
  options: MeasureCompositionOptions
): Promise<CompositionRun> {
  if (!Number.isInteger(options.iterations) || options.iterations < 1)
    throw new Error('Iterations must be a whole number of at least 1');
  const catalog: CatalogOptions = { catalog: options.catalog };
  const rootOutcome = await catalogResolver(catalog).resolve(options.root);
  if (rootOutcome.status !== 'resolved')
    throw new Error(`Root ${options.root} could not be resolved: ${rootOutcome.message}`);
  const authored = rootOutcome.snapshot.links?.compositions.find(
    (candidate) => candidate.id === options.composition
  );
  if (!authored) throw new Error(`Unknown composition: ${options.composition} in ${options.root}`);
  const participating = [options.root, ...authored.projects.map((project) => project.model)].filter(
    (model, index, all) => all.indexOf(model) === index
  );

  clearModelCache();
  const coldStart = performance.now();
  for (const model of participating)
    await loadDirectory((await resolveProject(model, catalog)).entry.directory);
  const coldParseMs = performance.now() - coldStart;

  await compositionPass(options.root, options.composition, participating, catalog);
  const runs: CompositionPass[] = [];
  for (let i = 0; i < options.iterations; i++)
    runs.push(await compositionPass(options.root, options.composition, participating, catalog));
  const last = runs[runs.length - 1];
  const cache = modelCacheStats();
  const open = last.composed.projects.filter((project) => project.diagram !== null);
  const counts: CompositionCounts = {
    projects: last.composed.projects.length,
    loadedElements: last.snapshots.reduce(
      (total, snapshot) => total + snapshot.model.elements.length,
      0
    ),
    loadedRelationships: last.snapshots.reduce(
      (total, snapshot) => total + snapshot.model.relationships.length,
      0
    ),
    visibleNodes: open.reduce((total, project) => total + project.diagram!.nodes.length, 0),
    visibleEdges: open.reduce((total, project) => total + project.diagram!.edges.length, 0),
    bridges: last.composed.bridges.length,
    stubs: last.composed.stubs.length,
    diagnostics: last.composed.diagnostics.length,
    cacheHits: cache.hits,
    cacheMisses: cache.misses,
    cacheEntries: cache.size
  };
  const row: CompositionRow = {
    model: options.label,
    view: 'composition',
    engine: last.engine,
    source: `${options.root}::${options.composition}`,
    nodes: counts.visibleNodes,
    edges: counts.visibleEdges,
    width: round(last.composed.width, 2),
    height: round(last.composed.height, 2),
    iterations: options.iterations,
    stages: summarize(runs),
    fingerprint: compositionFingerprint(last.composed),
    quality: composedQuality(last.composed),
    counts,
    bytes: last.bytes,
    coldParseMs: round(coldParseMs, 3),
    commit: null,
    timestamp: new Date().toISOString()
  };
  return { row, composed: last.composed };
}

export interface CompositionStageDelta {
  stage: CompositionStage;
  baseline: number | null;
  current: number | null;
  delta: number | null;
}

export interface CompositionRowComparison {
  key: string;
  model: string;
  view: string;
  engine: string;
  status: 'compared' | 'added' | 'missing';
  fingerprintChanged: boolean;
  baselineFingerprint: string | null;
  fingerprint: string | null;
  stages: CompositionStageDelta[];
}

export interface CompositionComparison {
  rows: CompositionRowComparison[];
  geometryChanged: boolean;
}

/** Baseline comparison for composition rows, including the composition-only stages. */
export function compareCompositionRows(
  current: readonly CompositionRow[],
  baseline: readonly CompositionRow[]
): CompositionComparison {
  const baselineByKey = new Map(baseline.map((row) => [rowKey(row), row]));
  const rows: CompositionRowComparison[] = current.map((row) => {
    const previous = baselineByKey.get(rowKey(row));
    const stages: CompositionStageDelta[] = [];
    for (const stage of COMPOSITION_STAGES) {
      const before = previous?.stages[stage]?.p50 ?? null;
      const after = row.stages[stage]?.p50 ?? null;
      if (before === null && after === null) continue;
      stages.push({
        stage,
        baseline: before,
        current: after,
        delta: before === null || after === null ? null : round(after - before, 3)
      });
    }
    return {
      key: rowKey(row),
      model: row.model,
      view: row.view,
      engine: row.engine,
      status: previous ? 'compared' : 'added',
      fingerprintChanged: previous ? previous.fingerprint !== row.fingerprint : false,
      baselineFingerprint: previous?.fingerprint ?? null,
      fingerprint: row.fingerprint,
      stages
    };
  });
  const measured = new Set(current.map((row) => rowKey(row)));
  for (const row of baseline)
    if (!measured.has(rowKey(row)))
      rows.push({
        key: rowKey(row),
        model: row.model,
        view: row.view,
        engine: row.engine,
        status: 'missing',
        fingerprintChanged: false,
        baselineFingerprint: row.fingerprint,
        fingerprint: null,
        stages: []
      });
  return { rows, geometryChanged: rows.some((row) => row.fingerprintChanged) };
}
