#!/usr/bin/env node
// Generates the CLI reference from the CLI's own --help output, so the document
// cannot drift from the commands without tests/docs.test.ts noticing.
import { execFileSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const CLI_REFERENCE_PATH = join(ROOT, 'docs', 'guides', 'active', 'cli.md');

/** One command whose --help text differs from its parent's. */
export interface HelpGroup {
  /** Command words after `bin/fractal`; empty for the top level. */
  argv: string[];
  help: string;
  /** Subcommands that print exactly this group's help text. */
  shared: string[];
  /** Subcommands with their own help text, in command-list order. */
  groups: HelpGroup[];
}

export type HelpRunner = (argv: string[]) => string;

function runHelp(argv: string[]): string {
  return execFileSync(join(ROOT, 'bin', 'fractal'), [...argv, '--help'], {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  }).trimEnd();
}

/** Command names listed under a `Commands:` heading, in order. */
export function listCommands(helpText: string): string[] {
  const lines = helpText.split('\n');
  const start = lines.findIndex((line) => /^Commands:\s*$/.test(line));
  if (start < 0) return [];
  const commands: string[] = [];
  for (const line of lines.slice(start + 1)) {
    const match = /^\s+(\S+)/.exec(line);
    if (!match) break;
    commands.push(match[1]);
  }
  return commands;
}

/** Capture --help for a command and, recursively, every subcommand it lists. */
export function captureHelp(argv: string[] = [], run: HelpRunner = runHelp): HelpGroup {
  return capture(argv, run(argv), run);
}

function capture(argv: string[], help: string, run: HelpRunner): HelpGroup {
  const group: HelpGroup = { argv, help, shared: [], groups: [] };
  for (const command of listCommands(help)) {
    const subArgv = [...argv, command];
    const subHelp = run(subArgv);
    if (subHelp === help) group.shared.push(command);
    else group.groups.push(capture(subArgv, subHelp, run));
  }
  return group;
}

function code(name: string): string {
  return `\`${name}\``;
}

function renderGroup(group: HelpGroup): string[] {
  const lines = [`## fractal ${group.argv.join(' ')}`.trimEnd(), '', '```text', group.help, '```'];
  if (group.shared.length) {
    const names = group.shared.map(code).join(', ');
    lines.push('', `${names} print this same text with \`--help\`.`);
  }
  for (const sub of group.groups) lines.push('', ...renderGroup(sub));
  return lines;
}

export function renderCliReference(group: HelpGroup, generator = 'scripts/docs.ts'): string {
  return [
    '# CLI reference',
    '',
    `<!-- Generated by ${generator}. Do not edit by hand; run \`npm run docs\`. -->`,
    '',
    'This page is the `--help` output of every `bin/fractal` command, captured by `npm run docs`.',
    '`tests/docs.test.ts` fails when it is out of date, so a CLI change is not finished until this',
    'file is regenerated and committed.',
    '',
    '`npm run cli --` accepts the same model commands and options as `bin/fractal`.',
    'Use `bin/fractal service ...` for service management. The wrapper runs from any directory',
    'and keeps stdout free of the npm banner; `service` is routed to',
    '`scripts/service.mjs`, everything else to `scripts/fractal.ts`. Errors are JSON on stderr with',
    'a nonzero exit.',
    '',
    ...renderGroup(group),
    ''
  ].join('\n');
}

export async function writeCliReference(
  path = CLI_REFERENCE_PATH,
  run: HelpRunner = runHelp
): Promise<string> {
  const markdown = renderCliReference(captureHelp([], run));
  await writeFile(path, markdown);
  return markdown;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeCliReference()
    .then(() => console.log(`Wrote ${relative(process.cwd(), CLI_REFERENCE_PATH)}`))
    .catch((error) => {
      console.error(JSON.stringify({ error: error.message }));
      process.exitCode = 1;
    });
}
